# Generated by Django 3.2 on 2021-04-27 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.CharField(default='admin', max_length=150),
        ),
        migrations.AddField(
            model_name='categories',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 7, 5, 7, 318278, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='modified_by',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='categories',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 7, 5, 14, 272733, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.CharField(default='electronics', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
