# Generated by Django 3.2 on 2021-05-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userwishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwishlist',
            options={'verbose_name': 'wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelTable(
            name='userwishlist',
            table='user_wishlist',
        ),
    ]
