# Generated by Django 3.2 on 2021-05-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210504_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributeassociation',
            old_name='product_attribute_association_id',
            new_name='product_attribute_value_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='modify_by',
            new_name='modified_by',
        ),
    ]
